### ISSUE TITLE
Exhaust/Particle Effect for mini Karbonite engine excessively large.

### ISSUE THREAD

**Issue by Celann-** [BobPalmer/KarbonitePlus#27]
Although I realize karbonite engines tend to have rather large exhaust plumes, the exhaust trail for the mini karbonite engine added by K+ appears to be many times the size it should be in relation to other engines and their respective exhaust trails.

At low levels of thrust this is not too obvious but on max thrust it's rather over sized.

**Comment by BobPalmer** [comment]
So do I - closing ;)
