### ISSUE TITLE
Karbonite tanks instantly full

### ISSUE THREAD

**Issue by stefborg** [BobPalmer/KarbonitePlus#29]
Since this is supposed to be fixed in Karbonite version 0.4.4, I guess it's an issue with the mini Karbonite drill from Karbonite+ (0.2.3). I use it on a Minmus lander, and whenever it comes back down from the orbital station to get another load the tanks are instantly filled upon starting the extraction. The first time it worked fine.

**Comment by BobPalmer** [comment]
Fixed in Regolith.
