### ISSUE TITLE
Missing parts in career

### ISSUE THREAD

**Issue by Prototype2001** [BobPalmer/KarbonitePlus#37]
Some items missing such as torch engines in career, need CTT to see the tech to obtain them, vanilla tech for torch doesn't exist thus they are unobtainable.

Also theres an issue w. overpriced, free parts, and negative cost parts again, im guessing thats firespitter, this issue pretty much affects all USI mods.

**Comment by blueshibe** [comment]
Also, with CTT enabled, the torch drives are there, but for some strange reason the drills are missing from the VAB parts list.

They show up in the node fuelSystems, but for whatever reason don't show in the parts list in the VAB.

Not sure if this is a Karbonite or CTT issue.

**Comment by BobPalmer** [comment]
Fixed in next release
