### ISSUE TITLE
Upgrade path for deprecated parts

### ISSUE THREAD

**Issue by Falkvinge** [BobPalmer/KarbonitePlus#45]
This is not an issue with the current state of K+ as much as an issue with how K+ changes state.

**Use case:** Long-time player starts up KSP in the morning, after a routine upgrade of their system and all components, including KSP mods (via CKAN - the user just hit the "upgrade all" routinely). As KSP boots, it complains a lot of ships can't be loaded as some parts are missing from their Career savegame - which is odd, as the user hasn't removed any mod. 

As the user enters Tracking, they notice that their Eeloo mining operation has vanished, along with the Karborundum refuel hub in orbit around Kerbin with several hundred thousand units of K+, a number of science expeditions, and two large colony ships in orbit around Duna and Jool. As the user has entered Tracking, KSP has already persisted the new version of the savegame without these ships in its universe.

The cause of this is that two parts that the user had on many ships - the 5-meter Torch drive (on colony ships and the refuel hub, built on the FTT 5-meter frame) and the radial K+ tank (throughout the mining colony and on many smaller ships) - had been removed from the K+ mod in a breaking change on the routine update performed.

**Suggested upgrade path:** When a mod maker wants to deprecate parts, a better upgrade path is to mark them "Unresearchable" in the tech tree. This will remove them from sight and mind but will not cause untold hundreds of hours of gametime to be lost - like when a regular product becomes unavailable, those items do not disappear, but keep working even if they're not available for sale any longer. For file system hygiene, they could also be put in a "Deprecated" folder in the mod folder, as opposed to being removed from KSP altogether.

**It is not reasonable for the user to expect or anticipate a routine upgrade of their system components to break the persistent KSP universe.**

**Comment by chrissnave** [comment]
I agree, when possible, an update should not be ship-breaking/save-breaking but I'm guessing at some point, old parts do need to be removed from the game as they take up RAM even if they're not used.

I'd suggest hitting Alt F9 at least once per session to save a sequentially numbered copy of your game's progress. That will allow you to recover your game if & when something like this happens. In the situation you've described I'd suggest temporarily reverting to the previous Karbonite Plus version, reloading your last saved game (assuming you've been saving them as you go) & then removing any discontinued parts from your ships/bases (KAS has this functionality I believe). Then install the K+ update & your ships should load okay. Obviously you'll need to replace the missing parts somehow. Easiest way would be to rework the entire vessel in the VAB then hyper-edit that to the location of your broken ship. Transfer the crew over & then terminate the old ship. Using hyper-edit to fix game glitches is not cheating in my opinion.

**Comment by BobPalmer** [comment]
CKAN is not supported.  KSP-AVC is.  It will notify you when there is a new release, at which point the best move is to look at the forum thread and see the change log - I usually issue very large warnings for part deprecation, and most of these take place around major KSP releases.  Closing as this is more of a discussion than a specific issue.
