### ISSUE TITLE
KA.Tank.0x: Cannot replace texture as cannot find texture 'Tank_00' to replace

### ISSUE THREAD

**Issue by RealKolago** [BobPalmer/KarbonitePlus#49]
PartLoader: Compiling Part 'UmbraSpaceIndustries/KarbonitePlus/Parts/KA_Tank_02/KA_Tank_02'
PartCompiler: Cannot replace texture as cannot find texture 'Tank_00' to replace

PartLoader: Compiling Part 'UmbraSpaceIndustries/KarbonitePlus/Parts/KA_Tank_03/KA_Tank_03'
PartCompiler: Cannot replace texture as cannot find texture 'Tank_00' to replace

PartLoader: Compiling Part 'UmbraSpaceIndustries/KarbonitePlus/Parts/KA_Tank_04/KA_Tank_04'
PartCompiler: Cannot replace texture as cannot find texture 'Tank_00' to replace

**Comment by BobPalmer** [comment]
These tanks have been deprecated, closing
